version: '3'
services:
  mysql:
    image: hypriot/rpi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  app:
    build: .
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 1
      MYSQL_DATABASE_PASSWORD: root
    ports:
      - '3001:3000'
    volumes:
      - .:/roselist:delegated
    links:
      - mysql:mysql
    depends_on:
      - mysql
    stdin_open: true
    tty: true
